#!/usr/bin/env bash
# =====================================================================
# ALTIVEX Demo Branch — Bootstrap script
# ---------------------------------------------------------------------
# Jalankan SATU KALI untuk generate credential demo yang terpisah dari
# prod. Idempotent: aman dijalankan ulang.
#
# Cara pakai:
#   cd ~/ALTIVEX
#   bash deployment/demo-branch/bootstrap-demo.sh
# =====================================================================

set -euo pipefail

# ---------------------------------------------------------------------
# CRLF safety: kalau script ini di-clone via Windows tanpa .gitattributes
# yang force LF, file ini bisa punya \r\n endings yang bikin bash gagal
# parse heredoc + path. Self-heal: rewrite diri sendiri ke LF kalau perlu.
# ---------------------------------------------------------------------
SELF="$(readlink -f "$0")"
if grep -q $'\r' "$SELF" 2>/dev/null; then
    echo "🔧 Fixing CRLF line endings di $SELF..."
    sed -i 's/\r$//' "$SELF"
    echo "   Re-running script dengan line endings yang sudah benar..."
    exec bash "$SELF" "$@"
fi

# Pindah ke folder demo-branch
SCRIPT_DIR="$(dirname "$SELF")"
cd "$SCRIPT_DIR"

ENV_FILE=".env.demo"
PASSWD_DIR="mosquitto-demo/config"
PASSWD_FILE="$PASSWD_DIR/passwd"
CONF_FILE="$PASSWD_DIR/mosquitto.conf"
OVERRIDE_DIR="frontend-override"

echo "🚀 ALTIVEX Demo Branch Bootstrap"
echo "================================="

# ---------------------------------------------------------------------
# 1. Generate .env.demo
# ---------------------------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
    echo "✅ $ENV_FILE sudah ada, skip regenerate."
    echo "   (Hapus file ini kalau mau generate ulang)"
else
    echo "📝 Generate $ENV_FILE..."

    POSTGRES_USER="altivex_demo"
    POSTGRES_PASSWORD=$(openssl rand -hex 16)
    POSTGRES_DB="altivex_demo_db"
    MQTT_USERNAME="altivex_demo"
    MQTT_PASSWORD=$(openssl rand -hex 16)
    API_AUTH_TOKEN=$(openssl rand -hex 32)
    # Login credential untuk operator demo — beda dari prod
    BASECAMP_USERNAME="demo"
    BASECAMP_PASSWORD=$(openssl rand -hex 12)

    cat > "$ENV_FILE" <<EOF
# Generated by bootstrap-demo.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# JANGAN COMMIT FILE INI.

DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres-demo:5432/$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

MQTT_BROKER_HOST=mosquitto-demo
MQTT_BROKER_PORT=1883
MQTT_USERNAME=$MQTT_USERNAME
MQTT_PASSWORD=$MQTT_PASSWORD

API_AUTH_TOKEN=$API_AUTH_TOKEN

BASECAMP_USERNAME=$BASECAMP_USERNAME
BASECAMP_PASSWORD=$BASECAMP_PASSWORD

SERIAL_PORT=/dev/null
RUST_LOG=info
EOF
    chmod 600 "$ENV_FILE"
    echo "✅ $ENV_FILE created."
fi

# Read values for next steps
# shellcheck disable=SC1090
source <(grep -E '^(MQTT_USERNAME|MQTT_PASSWORD|API_AUTH_TOKEN|BASECAMP_USERNAME|BASECAMP_PASSWORD)=' "$ENV_FILE")

# ---------------------------------------------------------------------
# 2. Generate mosquitto config + passwd
# ---------------------------------------------------------------------
mkdir -p "$PASSWD_DIR" "mosquitto-demo/data" "mosquitto-demo/log"

# Config file
cat > "$CONF_FILE" <<EOF
listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/passwd
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all
EOF

# Password file
if [[ -f "$PASSWD_FILE" ]] && grep -q "^${MQTT_USERNAME}:" "$PASSWD_FILE"; then
    echo "✅ mosquitto-demo passwd sudah ada, skip."
else
    echo "📝 Generate mosquitto-demo passwd..."
    docker run --rm -v "$PWD/$PASSWD_DIR:/work" -w /work \
        eclipse-mosquitto:2 \
        mosquitto_passwd -b -c passwd "$MQTT_USERNAME" "$MQTT_PASSWORD"
    chmod 600 "$PASSWD_FILE"
    echo "✅ mosquitto-demo passwd created."
fi

# Permission
if ! chown -R 1883:1883 "mosquitto-demo/data" "mosquitto-demo/log" 2>/dev/null; then
    sudo chown -R 1883:1883 "mosquitto-demo/data" "mosquitto-demo/log"
fi

# ---------------------------------------------------------------------
# 3. Placeholder GEO.json (kalau belum ada)
# ---------------------------------------------------------------------
mkdir -p "$OVERRIDE_DIR"
if [[ ! -f "$OVERRIDE_DIR/GEO.json" ]]; then
    echo "📝 Membuat placeholder GEO.json (ganti dengan peta gunung demo)..."
    cat > "$OVERRIDE_DIR/GEO.json" <<'GEOJSON'
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [106.9850, -6.7400],
          [106.9870, -6.7380],
          [106.9890, -6.7350],
          [106.9910, -6.7320],
          [106.9930, -6.7290]
        ]
      },
      "properties": {
        "name": "Jalur Demo",
        "type": "route"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [106.9850, -6.7400]
      },
      "properties": {
        "name": "Basecamp Demo",
        "type": "waypoint",
        "icon": "basecamp"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [106.9930, -6.7290]
      },
      "properties": {
        "name": "Puncak Demo",
        "type": "waypoint",
        "icon": "summit"
      }
    }
  ]
}
GEOJSON
    echo "   ⚠️  Ini placeholder! Ganti dengan GeoJSON jalur gunung yang sebenarnya."
fi

# ---------------------------------------------------------------------
# 4. Summary
# ---------------------------------------------------------------------
echo ""
echo "============================================================"
echo "✅ Demo branch bootstrap selesai!"
echo ""
echo "Domain: altivex-demo.duckdns.org"
echo ""
echo "Login Dashboard:"
echo "  Username: $BASECAMP_USERNAME"
echo "  Password: $BASECAMP_PASSWORD"
echo ""
echo "API Token: $API_AUTH_TOKEN"
echo ""
echo "MQTT (untuk ESP32 demo):"
echo "  Host: <IP_VM> atau altivex-demo.duckdns.org"
echo "  Port: 1885"
echo "  Username: $MQTT_USERNAME"
echo "  Password: $MQTT_PASSWORD"
echo "  Topic: altivex/sensor/data"
echo ""
echo "Langkah berikutnya:"
echo "  1. Ganti deployment/demo-branch/frontend-override/GEO.json"
echo "     dengan peta gunung untuk demo."
echo "  2. cd ~/ALTIVEX"
echo "     docker compose -f deployment/demo-branch/docker-compose.demo.yml \\"
echo "       --env-file deployment/demo-branch/.env.demo up -d --build"
echo "  3. Setup nginx reverse proxy untuk altivex-demo.duckdns.org → :8081"
echo "  4. Test: curl https://altivex-demo.duckdns.org/api/sensor/latest"
echo "============================================================"
