#!/usr/bin/env bash
# =====================================================================
# ALTIVEX — One-shot bootstrap script untuk VM cloud yang baru saja
# `git pull`. Jalankan SATU KALI saat first deploy.
# ---------------------------------------------------------------------
# Yang dilakukan:
#   1. Validasi `.env` (auto-backup + regenerate kalau format lama).
#   2. Generate `mosquitto/config/passwd` match `MQTT_USERNAME`/
#      `MQTT_PASSWORD` di `.env`.
#   3. Pastikan folder `mosquitto/log` + `mosquitto/data` writable
#      oleh container (uid 1883).
#   4. Print API token ke stdout supaya operator bisa simpan.
#
# Cara pakai:
#   cd <repo-root>             # GitHub clone, TIDAK harus altivex_backend
#   bash deployment/bootstrap.sh
#
# Idempotent: aman dijalankan ulang. Kalau `.env` sudah ada DAN sudah
# format baru, script tidak akan regenerate (secret tidak berubah).
# =====================================================================

set -euo pipefail

# ---------------------------------------------------------------------
# CRLF safety: kalau file ini di-clone via Windows tanpa .gitattributes,
# bash bisa salah parse \r di akhir baris. Self-heal sekali, lalu
# re-exec dengan endings yang sudah LF.
# ---------------------------------------------------------------------
SELF="$(readlink -f "$0")"
if grep -q $'\r' "$SELF" 2>/dev/null; then
    echo "🔧 Fixing CRLF line endings di $SELF..."
    sed -i 's/\r$//' "$SELF"
    echo "   Re-running script..."
    exec bash "$SELF" "$@"
fi

# Pindah ke parent dari script ini (= repo root) supaya path relatif
# konsisten apa pun cwd pemanggil.
cd "$(dirname "$(readlink -f "$0")")/.."

ENV_FILE=".env"
PASSWD_FILE="mosquitto/config/passwd"

# Daftar variable wajib di `.env`. Kalau salah satu hilang, file
# dianggap "format lama" → di-backup + regenerate.
REQUIRED_VARS=(
    "DATABASE_URL"
    "POSTGRES_USER"
    "POSTGRES_PASSWORD"
    "POSTGRES_DB"
    "MQTT_BROKER_HOST"
    "MQTT_BROKER_PORT"
    "MQTT_USERNAME"
    "MQTT_PASSWORD"
    "API_AUTH_TOKEN"
)

# ---------------------------------------------------------------------
# Helper: cek apakah .env punya semua variable wajib.
# ---------------------------------------------------------------------
env_is_complete() {
    local missing=()
    local var
    for var in "${REQUIRED_VARS[@]}"; do
        if ! grep -qE "^${var}=" "$ENV_FILE"; then
            missing+=("$var")
        fi
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        echo "⚠️  .env kekurangan variable: ${missing[*]}"
        return 1
    fi
    return 0
}

# ---------------------------------------------------------------------
# 1. Generate .env.
# ---------------------------------------------------------------------
NEED_GEN_ENV=0
if [[ ! -f "$ENV_FILE" ]]; then
    echo "📝 .env belum ada, generate baru..."
    NEED_GEN_ENV=1
elif ! env_is_complete; then
    BACKUP=".env.backup-$(date +%Y%m%d-%H%M%S)"
    echo "📦 .env format lama / kekurangan var. Backup ke $BACKUP, lalu regenerate."
    cp "$ENV_FILE" "$BACKUP"
    chmod 600 "$BACKUP"
    NEED_GEN_ENV=1
fi

if [[ "$NEED_GEN_ENV" -eq 1 ]]; then
    POSTGRES_USER="altivex_prod"
    # Pakai hex 16 byte (32 char) supaya URL-safe — base64 menghasilkan
    # `/` dan `+` yang harus di-encode di DATABASE_URL atau sqlx panic
    # `Configuration(InvalidPort)`. Hex aman di URL tanpa encoding.
    POSTGRES_PASSWORD=$(openssl rand -hex 16)
    POSTGRES_DB="altivex_db"
    MQTT_USERNAME="altivex_prod"
    MQTT_PASSWORD=$(openssl rand -hex 16)
    API_AUTH_TOKEN=$(openssl rand -hex 32)

    cat > "$ENV_FILE" <<EOF
# Generated by deployment/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# JANGAN COMMIT FILE INI. Sudah di-ignore oleh .gitignore.

DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

MQTT_BROKER_HOST=mosquitto
MQTT_BROKER_PORT=1883
MQTT_USERNAME=$MQTT_USERNAME
MQTT_PASSWORD=$MQTT_PASSWORD

API_AUTH_TOKEN=$API_AUTH_TOKEN

SERIAL_PORT=/dev/ttyUSB0
RUST_LOG=info
EOF
    chmod 600 "$ENV_FILE"
    echo "✅ .env created (chmod 600)."
else
    echo "✅ .env sudah lengkap, skip regenerate."
fi

# ---------------------------------------------------------------------
# Read final .env values (always, supaya step berikutnya konsisten).
# ---------------------------------------------------------------------
# shellcheck disable=SC1090
source <(grep -E '^(MQTT_USERNAME|MQTT_PASSWORD|API_AUTH_TOKEN)=' "$ENV_FILE")

# Sanity check — kalau setelah generate masih kosong, ada bug script.
: "${MQTT_USERNAME:?bootstrap bug: MQTT_USERNAME tidak ter-set di .env}"
: "${MQTT_PASSWORD:?bootstrap bug: MQTT_PASSWORD tidak ter-set di .env}"
: "${API_AUTH_TOKEN:?bootstrap bug: API_AUTH_TOKEN tidak ter-set di .env}"

# ---------------------------------------------------------------------
# 2. Generate mosquitto/config/passwd.
# ---------------------------------------------------------------------
mkdir -p mosquitto/config mosquitto/data mosquitto/log

if [[ -f "$PASSWD_FILE" ]] && grep -q "^${MQTT_USERNAME}:" "$PASSWD_FILE"; then
    echo "✅ mosquitto passwd sudah ada untuk user '$MQTT_USERNAME', skip regenerate."
else
    echo "📝 Generate mosquitto passwd untuk user '$MQTT_USERNAME'..."
    docker run --rm -v "$PWD/mosquitto/config:/work" -w /work \
        eclipse-mosquitto:2 \
        mosquitto_passwd -b -c passwd "$MQTT_USERNAME" "$MQTT_PASSWORD"
    chmod 600 "$PASSWD_FILE"
    echo "✅ mosquitto passwd created."
fi

# ---------------------------------------------------------------------
# 3. Permission untuk volume data/log Mosquitto.
# ---------------------------------------------------------------------
# eclipse-mosquitto image jalan sebagai uid 1883 — folder mounted dari
# host harus writable oleh uid itu.
if ! chown -R 1883:1883 mosquitto/data mosquitto/log 2>/dev/null; then
    sudo chown -R 1883:1883 mosquitto/data mosquitto/log
fi

# ---------------------------------------------------------------------
# 4. Print API token + langkah berikutnya.
# ---------------------------------------------------------------------
echo ""
echo "============================================================"
echo "✅ Bootstrap selesai."
echo ""
echo "API_AUTH_TOKEN (paste saat browser pertama kali tanya):"
echo ""
echo "   $API_AUTH_TOKEN"
echo ""
echo "Simpan token ini di password manager."
echo ""
echo "Langkah berikutnya:"
echo "  1. Edit deployment/Caddyfile → ganti 'altivex.example.com'"
echo "     dengan domain Anda."
echo "  2. docker compose -f docker-compose.yml \\"
echo "       -f deployment/docker-compose.prod.yml up -d --build"
echo "  3. docker compose logs -f backend"
echo "============================================================"
