#!/usr/bin/env bash
# =====================================================================
# ALTIVEX — One-shot bootstrap script untuk VM GCP yang baru saja
# `git pull`. Jalankan SATU KALI saat first deploy.
# ---------------------------------------------------------------------
# Yang dilakukan:
#   1. Generate `.env` dari template + secret acak (jika belum ada).
#   2. Generate `mosquitto/config/passwd` (match MQTT_USERNAME +
#      MQTT_PASSWORD di `.env`).
#   3. Pastikan folder `mosquitto/log` + `mosquitto/data` writable
#      oleh container.
#   4. Print API token ke stdout supaya operator bisa simpan
#      (token ini diminta browser saat akses dashboard pertama kali).
#
# Cara pakai:
#   cd ~/ALTIVEX/altivex_backend
#   bash deployment/bootstrap.sh
#
# Idempotent: aman dijalankan ulang. Kalau `.env` sudah ada,
# script akan SKIP regenerate (supaya secret tidak berubah).
# =====================================================================

set -euo pipefail

cd "$(dirname "$0")/.."  # cwd → altivex_backend/

ENV_FILE=".env"
PASSWD_FILE="mosquitto/config/passwd"

# ---------------------------------------------------------------------
# 1. Generate .env (idempotent — skip kalau sudah ada).
# ---------------------------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
    echo "✅ .env sudah ada, skip generate."
    # Baca nilai existing supaya bisa regenerate passwd kalau perlu.
    # shellcheck disable=SC1090
    source <(grep -E '^(MQTT_USERNAME|MQTT_PASSWORD|API_AUTH_TOKEN)=' "$ENV_FILE")
else
    echo "📝 Generate .env baru dengan secret acak..."

    # Secret yang aman: openssl rand. base64 utk password (length pendek
    # tapi entropy tinggi), hex utk token (audit trail mudah).
    POSTGRES_USER="altivex_prod"
    POSTGRES_PASSWORD=$(openssl rand -base64 18)
    POSTGRES_DB="altivex_db"
    MQTT_USERNAME="altivex_prod"
    MQTT_PASSWORD=$(openssl rand -base64 18)
    API_AUTH_TOKEN=$(openssl rand -hex 32)

    cat > "$ENV_FILE" <<EOF
# Generated by deployment/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# JANGAN COMMIT FILE INI. Sudah di-ignore oleh .gitignore.

DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

MQTT_BROKER_HOST=mosquitto
MQTT_BROKER_PORT=1883
MQTT_USERNAME=$MQTT_USERNAME
MQTT_PASSWORD=$MQTT_PASSWORD

API_AUTH_TOKEN=$API_AUTH_TOKEN

SERIAL_PORT=/dev/ttyUSB0
RUST_LOG=info
EOF
    chmod 600 "$ENV_FILE"
    echo "✅ .env created (chmod 600)."
fi

# ---------------------------------------------------------------------
# 2. Generate mosquitto/config/passwd.
# ---------------------------------------------------------------------
mkdir -p mosquitto/config mosquitto/data mosquitto/log
if [[ -f "$PASSWD_FILE" ]] && grep -q "^${MQTT_USERNAME}:" "$PASSWD_FILE"; then
    echo "✅ mosquitto passwd sudah ada untuk user '$MQTT_USERNAME', skip regenerate."
else
    echo "📝 Generate mosquitto passwd untuk user '$MQTT_USERNAME'..."
    docker run --rm -v "$PWD/mosquitto/config:/work" -w /work \
        eclipse-mosquitto:2 \
        mosquitto_passwd -b -c passwd "$MQTT_USERNAME" "$MQTT_PASSWORD"
    chmod 600 "$PASSWD_FILE"
    echo "✅ mosquitto passwd created."
fi

# ---------------------------------------------------------------------
# 3. Permission untuk volume data/log Mosquitto.
# ---------------------------------------------------------------------
# eclipse-mosquitto image jalan sebagai uid 1883.
chown -R 1883:1883 mosquitto/data mosquitto/log 2>/dev/null || \
    sudo chown -R 1883:1883 mosquitto/data mosquitto/log

# ---------------------------------------------------------------------
# 4. Print API token + langkah berikutnya.
# ---------------------------------------------------------------------
echo ""
echo "============================================================"
echo "✅ Bootstrap selesai."
echo ""
echo "API_AUTH_TOKEN (paste saat browser pertama kali tanya):"
echo ""
echo "   $API_AUTH_TOKEN"
echo ""
echo "Simpan token ini di password manager."
echo ""
echo "Langkah berikutnya:"
echo "  1. Edit deployment/Caddyfile → ganti 'altivex.example.com'"
echo "     dengan domain Anda."
echo "  2. docker compose -f docker-compose.yml \\"
echo "       -f deployment/docker-compose.prod.yml up -d --build"
echo "  3. docker compose logs -f backend"
echo "============================================================"
